### ISSUE TITLE
Reading Exceptions are not handled, instead the parser moves to the next file in queue.

### ISSUE THREAD

**Issue by girishtejwani** [uniVocity/univocity-parsers#140]

**Comment by girishtejwani** [comment]
S3 exceptions are not handled on reading

 Exception in thread "Character reading thread" java.lang.IllegalStateException: Error processing input
 at com.univocity.parsers.common.input.concurrent.ConcurrentCharLoader.run(ConcurrentCharLoader.java:92)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: java.net.SocketTimeoutException: Read timed out
 at java.net.SocketInputStream.socketRead0(Native Method)
 at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 at java.net.SocketInputStream.read(SocketInputStream.java:171)
 at java.net.SocketInputStream.read(SocketInputStream.java:141)
 at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
 at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
 at sun.security.ssl.InputRecord.read(InputRecord.java:532)
 at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
 at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
 at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)

**Comment by girishtejwani** [comment]
is it possible to stop the parser when it throws that error?

**Comment by jbax** [comment]
Thanks for reporting this one! It's fixed and will become available in version 2.4.0. I released a 2.4.0-SNAPSHOT build that includes this adjustment.

As a workaround for the current stable version, you can disable the input reading thread with `settings.setReadInputOnSeparateThread(false)`.
