### ISSUE TITLE
AnnotationHelper is not thread safe

### ISSUE THREAD

**Issue by yiftachdy** [uniVocity/univocity-parsers#146]
When using the [BeanWriterProcessor](http://github.com/uniVocity/univocity-parsers/tree/master/src/main/java/com/univocity/parsers/common/processor/BeanWriterProcessor.java) new logic to find annotations, cannot be called from multiple threads - `@Parsed` annotation is cast to `@Nested`

`java.lang.ClassCastException: com.sun.proxy.$Proxy30 cannot be cast to com.univocity.parsers.annotations.Nested
	at com.univocity.parsers.annotations.helpers.AnnotationHelper.getFieldSequence(AnnotationHelper.java:589) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.annotations.helpers.AnnotationHelper.deriveHeaderNamesFromFields(AnnotationHelper.java:498) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.common.CommonWriterSettings.configureFromAnnotations(CommonWriterSettings.java:170) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.common.CommonWriterSettings.runAutomaticConfiguration(CommonWriterSettings.java:158) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.common.CommonSettings.autoConfigure(CommonSettings.java:522) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.common.AbstractWriter.<init>(AbstractWriter.java:173) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.csv.CsvWriter.<init>(CsvWriter.java:66) ~[univocity-parsers-2.4.0.jar:2.4.0]
	at com.univocity.parsers.csv.CsvWriter.<init>(CsvWriter.java:56) ~[univocity-parsers-2.4.0.jar:2.4.0]`

**Comment by jbax** [comment]
Thanks for reporting this one! It's been fixed and a new 2.4.1-SNAPSHOT build has been released to include this adjustment.

Thank you for using our parsers!

**Comment by yiftachdy** [comment]
Hi @jbax, i cant seem to find the new build anywhere....

**Comment by jbax** [comment]
You can get snapshot builds from the maven central repository, or directly from [here](https://oss.sonatype.org/content/repositories/snapshots/com/univocity/univocity-parsers/2.4.1-SNAPSHOT/)

Regardless, version 2.4.1 has been released so you won't have to bother with it now. Thanks for using our parsers!
