### ISSUE TITLE
Concurrency problems

### ISSUE THREAD

**Issue by Chavjoh** [uniVocity/univocity-parsers#147]
Hello !

First of all, thank you for your tool. It's very useful and simple to implement.

I discovered a concurrency problem in AnnotationHelper (findAnnotation). Inside this helper you are using static variable to store the last annotation processed to return it more quickly for multiple identical calls. It's a good idea but you are forgetting about the ```synchronized``` keyword when you are using it.
```
if (annotatedElement.equals(lastProcessedElement) && annotationType == lastProcessedAnnotationType) {
	return (A) lastAnnotationFound;
}
```

**Example:** I have a model class that has ```@Parsed(index = xx)``` annotations on its attributes. And I'm parsing a lot of them inside separated thread. Of course, I'm using for each thread a different instance of the row processor and the parser. But because of the three lines described above, sometimes, I have errors because of identical indexes (because a thread enter in the ```if```, stop, and during the mean time, the ```lastAnnotationFound``` variable change and then the first thread will return the value of another field).

Here's the stack used during the parsing, just before the exception of identical indexes because the problem described above:
```
at com.univocity.parsers.common.processor.core.AbstractBeanConversionProcessor.validateMappings(AbstractBeanConversionProcessor.java:151)
at com.univocity.parsers.common.processor.core.AbstractBeanConversionProcessor.initialize(AbstractBeanConversionProcessor.java:78)
at com.univocity.parsers.common.processor.core.AbstractBeanProcessor.processStarted(AbstractBeanProcessor.java:67)
at com.univocity.parsers.common.processor.core.AbstractBeanListProcessor.processStarted(AbstractBeanListProcessor.java:81)
at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:245)
at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:111)
at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:626)
```

Can you correct this problem and make a patch release ?
Thank you in advance,
Best Regards.

**Comment by jbax** [comment]
It's been resolved already, see: https://github.com/uniVocity/univocity-parsers/issues/146

Have you tried the 2.4.1-SNAPSHOT build?

**Comment by Chavjoh** [comment]
Yes indeed I didn't see the other topic. It's now working with the snapshot build. Thank you.
When do you think the 2.4.1 version will be released ?

**Comment by jbax** [comment]
It's already available. Thanks for using our parsers!
