### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by glascaleia** [uniVocity/univocity-parsers#195]
Hi Guys,
i have this error trying to use CSVParser in MultiThread Context.
Caused by: java.lang.NullPointerException
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharInputReader.reloadBuffer(ConcurrentCharInputReader.java:109)
	at com.univocity.parsers.common.input.AbstractCharInputReader.updateBuffer(AbstractCharInputReader.java:190)
	at com.univocity.parsers.common.input.AbstractCharInputReader.nextChar(AbstractCharInputReader.java:246)
Regards
Giuseppe

**Comment by jbax** [comment]
You can't really use the parser in a multi-threaded context as the input buffer must be read and processed sequentially. The result of the next record depends on where previous ended. Calling `parseNext()` or other methods to obtain a record will only work sequentially. What you can do - and you are already doing by the error you got - is to run with `readInputOnSeparateThread=true`.

Hope this makes sense. Thank you for using our parsers!
