### ISSUE TITLE
Unable to use annotations on nested class

### ISSUE THREAD

**Issue by epryakhin** [uniVocity/univocity-parsers#210]
Hello everyone.

I have nested class annotated with univocity annotations and a upper class that exposes type of the nested. 
Example:

```
public class StbSetNetworkTypeCommand implements PojoOptionsCommand<StbSetNetworkTypeCommand.Request> {

  @Override
  public Class<Request> getOptionsType() {
    return Request.class;
  }

  @Getter(AccessLevel.PACKAGE) // lombok
  public class Request {

    @Parsed(index = 0)
    @Trim
    private String activationNumber;
    @Parsed(index = 1)
    @Trim
    private String resourceSpec;
    @Parsed(index = 2)
    @Trim
    private String networkType;

  }
}
```

I also have the boilerplate code that parses the string using exposed type. 
Example:

```
BeanListProcessor<T> blp = new BeanListProcessor<>(command.getOptionsType());

CsvParserSettings settings = new CsvParserSettings();
settings.setProcessor(blp);
settings.setHeaderExtractionEnabled(false);

CsvParser parser = new CsvParser(settings);
parser.parse(new StringReader(options));

command.setOptions(blp.getBeans().get(0));
```

When I try to run this code, I get an error.

```
Exception in thread "main" com.univocity.parsers.common.DataProcessingException: Unable to instantiate class 'StbSetNetworkTypeCommand$Request'
Internal state when error was thrown: line=1, column=0, record=1, charIndex=5, headers=[1, 2, 3], row=[1, 2, 3]
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:506)
	at com.univocity.parsers.common.processor.core.AbstractBeanProcessor.rowProcessed(AbstractBeanProcessor.java:54)
	at com.univocity.parsers.common.Internal.process(Internal.java:21)
	at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:596)
	at com.univocity.parsers.common.AbstractParser.handleEOF(AbstractParser.java:206)
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:141)
        ...
Caused by: java.lang.InstantiationException: StbSetNetworkTypeCommand$Request
	at java.lang.Class.newInstance(Class.java:427)
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:504)
	... 7 more
Caused by: java.lang.NoSuchMethodException: StbSetNetworkTypeCommand$Request.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 8 more
```

If I move the nested class to upper-level class everything works fine on both java 8 and 9.
This behavior exists on Oracle JVM 8 and 9.

Does this behavior is an issue, or I'm doing something wrong?
Thanks in advance.

**Comment by jbax** [comment]
Try declaring your request class as static.
