### ISSUE TITLE
TSV parser OutOfMemory

### ISSUE THREAD

**Issue by zasbit** [uniVocity/univocity-parsers#221]
Hi,

I'm trying to read a bug tsv file and is always giving the following error:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.univocity.parsers.common.input.DefaultCharAppender.getAndReset(DefaultCharAppender.java:114)
        at com.univocity.parsers.common.ParserOutput.valueParsed(ParserOutput.java:308)
        at com.univocity.parsers.tsv.TsvParser.parseField(TsvParser.java:115)
        at com.univocity.parsers.tsv.TsvParser.parseRecord(TsvParser.java:71)
        at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:495)
        at pt.farmodietica.output.EficienciaRun.parseFileTSV1(EficienciaRun.java:373)
        at pt.farmodietica.output.EficienciaRun.Run(EficienciaRun.java:58)
        at pt.farmodietica.output.Eficiencia.main(Eficiencia.java:6)

The code to read the file is:
TsvParser parser = new TsvParser(settings);
			InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream(filename), "UTF-8");
			parser.beginParsing(inputStreamReader);
			String[] record = parser.parseNext();
			while (record != null) {
				allRows.add(record);
				record = parser.parseNext();
			}

What I need to do to fix?

Thanks you

**Comment by jbax** [comment]
It looks like you have a lot of records to process. In this case adding everything to a list in memory will be a problem, as your `allRows` list will use up everything. 

Just avoid doing `allRows.add(record);` if you can help it, or simply raise your heap size using the  `Xms` and `Xmx`  flags.

Thank you for using our parsers!

**Comment by yuezheng** [comment]
Hello @jbax,
I also had a memory overflow problem when parse CSV file. I try to parse 1GB CSV file(1 million
rows), code just like:
`      
        
        CsvParserSettings parserSettings = new CsvParserSettings();
        parserSettings.getFormat().setLineSeparator("\n");
        parserSettings.setHeaderExtractionEnabled(true);
        ColumnProcessor rowProcessor = new ColumnProcessor();
        parserSettings.setProcessor(rowProcessor);
        CsvParser parser = new CsvParser(parserSettings);
        int count = 0;
        InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream("file_path"), "UTF-8");
        parser.beginParsing(inputStreamReader);
        String[] record = parser.parseNext();
        while (record != null) {
            System.out.println(record);
            record = parser.parseNext();
            count += 1;
            System.out.println("" + count);
        }
`

I've noticed that as the program runs, memory increases until an exception is thrown: OutOfMemoryError.
I also try use the "parser.iterateRecords", but result was the same.
How can I avoid this problem？
Thank you.

**Comment by jbax** [comment]
Use the batched colum  processor. The ColumnProcessor implementation stores
everything in memory

**Comment by jbax** [comment]
Also it doesn't look like you need a column processor at all as you are not
using it.

**Comment by yuezheng** [comment]
Great, Thanks!

**Comment by cozos** [comment]
Hi @jbax, 

I am getting this error too `java.lang.OutOfMemoryError: Java heap space` in Apache Spark:

```
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:369)
	at com.univocity.parsers.common.AbstractParser.handleEOF(AbstractParser.java:205)
	at com.univocity.parsers.common.AbstractParser.parseLine(AbstractParser.java:665)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser$$anonfun$4.apply(UnivocityParser.scala:207)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser$$anonfun$4.apply(UnivocityParser.scala:207)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser.parse(UnivocityParser.scala:218)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser$$anonfun$9.apply(UnivocityParser.scala:346)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser$$anonfun$9.apply(UnivocityParser.scala:346)
	at org.apache.spark.sql.execution.datasources.FailureSafeParser.parse(FailureSafeParser.scala:62)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser$$anonfun$parseIterator$1.apply(UnivocityParser.scala:350)
	at org.apache.spark.sql.execution.datasources.csv.UnivocityParser$$anonfun$parseIterator$1.apply(UnivocityParser.scala:350)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:130)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:216)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:297)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$2.apply(ShuffleExchangeExec.scala:266)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

What I'm confused about is, I think I actually have _lots_ of heap space remaining based on GC logs:

```
   [Eden: 0.0B(17920.0M)->0.0B(17920.0M) Survivors: 0.0B->0.0B Heap: 249.3G(350.0G)->249.3G(350.0G)]
 [Times: user=0.07 sys=0.01, real=0.02 secs] 
java.lang.OutOfMemoryError: Java heap space
```

Could there be some off-heap thing going on?

Thanks

**Comment by jbax** [comment]
Hi @cozos, I'm not sure what spark does but the parser itself should not run out of memory that easily.

My first suggestion is to check if the input matches the format.

You might be parsing something that does not correspond with the configured format. In that case the parser will keep accumulating values in an internal char[]. That will grow until you reach Integer.MAX_VALUE and then you will get an error because you can't have an array bigger than that. Depending on your java version, you might get an exception with this misleading message: "java.lang.OutOfMemoryError: Java heap space" (I guess java 6 or 7, but I'm not 100% sure), even though you have enough memory to spare.

Hope this helps.

**Comment by jbax** [comment]
You can use these two settings to help:

```
parserSettings.setMaxCharsPerColumn(<a large number>);

parserSettings.setMaxColumns(<a large number>);
```

If the limit is reached you will get a parsing exception that might help you.

Also, try using the parser directly instead of through spark to see if the error is reproducible. If it doesn't happen then the issue is with spark itself.

**Comment by cozos** [comment]
Thank you for the help. I will try this out!
