### ISSUE TITLE
Default Boolean parsing should be case insensitive

### ISSUE THREAD

**Issue by mlvn23** [uniVocity/univocity-parsers#23]
It took me an hour to figure this out, so I thought it might be a good idea to make the default Boolean parser to be case insensitive. 

At first, I tried to create my own case-insensitive MyBooleanConversion, but apparently the library would fail because it's trying to apply its own BooleanConversion to the output of MyBooleanConversion, which is no longer a String:

```
Caused by: java.lang.IllegalStateException: Error converting value 'true' using conversion com.univocity.parsers.conversions.BooleanConversion
        at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:153)
        at com.univocity.parsers.common.processor.ConversionProcessor.applyConversions(ConversionProcessor.java:129)
        at com.univocity.parsers.common.processor.BeanConversionProcessor.createBean(BeanConversionProcessor.java:283)
        at com.univocity.parsers.common.processor.BeanProcessor.rowProcessed(BeanProcessor.java:51)
        at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:89)
        at CsvUtils$.fromCsv(CsvUtils.scala:24)
        at UnivocityTest$.delayedEndpoint$UnivocityTest$1(UnivocityTest.scala:5)
        at UnivocityTest$delayedInit$body.apply(UnivocityTest.scala:3)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at UnivocityTest$.main(UnivocityTest.scala:3)
        at UnivocityTest.main(UnivocityTest.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at com.univocity.parsers.conversions.ObjectConversion.execute(ObjectConversion.java:29)
        at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:151)
        at com.univocity.parsers.common.processor.ConversionProcessor.applyConversions(ConversionProcessor.java:129)
        at com.univocity.parsers.common.processor.BeanConversionProcessor.createBean(BeanConversionProcessor.java:283)

```

I finally figured out that there's couple of options: use @LowerCase or enumerate them using @BooleanString or BooleanConversion, etc. But I think it's more intuitive if the library can handle it without any annotations except for @Parsed. IIRC, this is how Jackson behaves.

**Comment by jbax** [comment]
Thank you for your suggestion. I'll make it case insensitive in version 1.5.3 (to be released in a couple of days).

In regards to the issue you mentioned with the custom `MyBooleanConversion`, have you tried with the latest version? A similar error was happening on eariler versions. Please open a new issue for if it is still happening for you on 1.5.2.

**Comment by jbax** [comment]
Fixed in this commit:

https://github.com/uniVocity/univocity-parsers/commit/18fdda84aa5e23ebb8376a274bc0150b635b5b1e

**Comment by jbax** [comment]
Version 1.5.3 has been just released with a fix for issue and some error reporting enhancements.

It may take a few hours before the artifact is available through maven central, but you can already download it directly from [here](http://oss.sonatype.org/content/repositories/releases/com/univocity/univocity-parsers/1.5.3/univocity-parsers-1.5.3.jar)

**Comment by mlvn23** [comment]
Wow, thanks for the super fast fix!
