### ISSUE TITLE
Unsupported charset (IBM424_rtl)

### ISSUE THREAD

**Issue by ludoo0d0a** [uniVocity/univocity-parsers#243]
I found a case where a file was encoded in IBM424_rtl.
It could be because of _rtl at the end. charset should be IBM424, I think. 
May be need to strip some like ICU does 
http://icu-project.org/~yoshito/jacoco_57.1/com.ibm.icu.text/CharsetMatch.java.html#108

`java.nio.charset.UnsupportedCharsetException: IBM424_rtl
	at java.nio.charset.Charset.forName(Charset.java:531) ~[?:1.8.0_31]
	at com.univocity.parsers.common.ArgumentUtils.newReader(ArgumentUtils.java:330) ~[univocity-parsers-2.5.9.jar:?]
	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:734) ~[univocity-parsers-2.5.9.jar:?]`

**Comment by jbax** [comment]
Except for unicode with BOM markers, the parser doesn't do anything to handle the charset. Specifically, this is non-standard encoding the Java does not recognize.

Not sure how I can help you here

**Comment by jbax** [comment]
Closing as there's nothing we can do.
