### ISSUE TITLE
NumberFormatException and others

### ISSUE THREAD

**Issue by ozzioma** [uniVocity/univocity-parsers#273]
Hi,
Thanks for this library.

I'm having issues parsing a CSV file, actually NYSE stock prices data sourced from Kaggle.
I using version 2.7.4.

It fails with this error
```
2010-10-04, columnName=volume
2016-01-05 00:00:00, columnIndex=6
	at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:273)
	at com.univocity.parsers.common.DefaultConversionProcessor.applyConversions(DefaultConversionProcessor.java:120)
	at com.univocity.parsers.common.processor.core.BeanConversionProcessor.createBean(BeanConversionProcessor.java:522)
	at com.univocity.parsers.common.processor.core.AbstractBeanProcessor.rowProcessed(AbstractBeanProcessor.java:54)
	at com.univocity.parsers.common.Internal.process(Internal.java:30)
	at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:682)
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:135)
	at com.ozzydemos.bootdemo1.CsvLoader.LoadPrices(CsvLoader.java:36)
	at com.ozzydemos.bootdemo1.DemoApp.LoadCsv(DemoApp.java:24)
	at com.ozzydemos.bootdemo1.DemoApp.main(DemoApp.java:17)
Caused by: java.lang.NumberFormatException: For input string: "3849500.0
2010-10-04"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at com.univocity.parsers.conversions.DoubleConversion.fromString(DoubleConversion.java:47)
	at com.univocity.parsers.conversions.DoubleConversion.fromString(DoubleConversion.java:23)
	at com.univocity.parsers.conversions.ObjectConversion.fromInput(ObjectConversion.java:69)
	at com.univocity.parsers.conversions.ObjectConversion.fromInput(ObjectConversion.java:29)
	at com.univocity.parsers.conversions.NullConversion.execute(NullConversion.java:66)
	at com.univocity.parsers.conversions.ObjectConversion.execute(ObjectConversion.java:58)
	at com.univocity.parsers.conversions.ObjectConversion.execute(ObjectConversion.java:29)
	at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:267)
	... 9 more


```

This is the line where it is failing, the last line below for ticker "CCL"
```
2010-10-04,CAG,22.15,22.0,21.909998,22.199999,4487700.0
2010-10-04,CAH,32.68,32.18,31.879999,32.82,2498800.0
2010-10-04,CAT,78.019997,77.269997,76.510002,78.260002,6418700.0
2010-10-04,CB,58.080002,58.099998,57.75,58.470001,1235000.0
2010-10-04,CBG,18.139999,17.690001,17.65,18.200001,4103300.0
2010-10-04,CBS,16.32,16.389999,15.97,16.389999,12959700.0
2010-10-04,CCI,44.110001,43.610001,43.529999,44.34,2069000.0
2010-10-04,CCL,38.27,38.09,37.650002,38.560001,3849500.0
```

What could be wrong?

This is the entity class below

```
@Data
public class Prices
{
    @Parsed(index = 0)
    @Format(formats = {"yyyy-MM-dd", "dd/MM/yyyy"}, options = "locale=en;lenient=false")
    @NullString(nulls = "-")
    private Date pricedate;

    @Parsed(index = 1)
    private String symbol;

    @Parsed(index = 2)
    @Format(formats = {"#0,00"}, options = "decimalSeparator=,")
    private double open;

    @Parsed(index = 3)
    @Format(formats = {"#0,00"}, options = "decimalSeparator=,")
    private double close;

    @Parsed(index = 4)
    @Format(formats = {"#0,00"}, options = "decimalSeparator=,")
    private double low;

    @Parsed(index = 5)
    @Format(formats = {"#0,00"}, options = "decimalSeparator=,")
    private double high;

    @Parsed(index = 6)
    //@Format(formats = {"###","#0","#0"}, options = "decimalSeparator=,")
    private double volume;

}

```

This is where the file data is loaded

```
public static void LoadPrices() throws IOException {
        try (
                Reader reader = Files.newBufferedReader(Paths.get(csvpathPrices));
        ) {
            BeanListProcessor<Prices> rowProcessor = new BeanListProcessor<Prices>(Prices.class);

            CsvParserSettings settings = new CsvParserSettings();
            settings.setRowProcessor(rowProcessor);
            settings.setHeaderExtractionEnabled(true);
            settings.setMaxColumns(1000000);
            settings.setIgnoreLeadingWhitespacesInQuotes(false);
            settings.setIgnoreTrailingWhitespacesInQuotes(false);
            settings.trimQuotedValues(true);

            CsvParser parser = new CsvParser(settings);
            parser.parse(reader);

            List<Prices> allRows = rowProcessor.getBeans();

            for (Prices price:allRows )
            {
                System.out.println(price);
                //System.out.println("==========================");
            }
        }

    }

```

Thanks

**Comment by ozzioma** [comment]
Also, what's the difference between

settings.setMaxColumns(n);
and 
settings.setNumberOfRecordsToRead(n);

I'm assuming MaxColumns means the total number of columns per row of data right?
If I do this for the above dataset which has just 7 columns
settings.setMaxColumns(10);

Running the demo bombs with this exception
```
com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexOutOfBoundsException - 10
Hint: Number of columns processed may have exceeded limit of 10 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have

```

What could be wrong please?
I using version 2.7.4, Intellij for some reason cannot import 2.7.5 from Maven.

**Comment by jbax** [comment]
Thanks for the detailed information.

It looks like your errors are coming from not configuring the CSV format according to the data you are processing. Specifically, the line ending character is not configured correctly. That's why 
`settings.setMaxColumns(10);` will cause trouble: the parser will never find the end of the record and keep going adding stuff to the same one. We created this setting specifically to prevent the parser going ahead when the configured format does not match the input.

I assume you are on windows, where the default line ending is `\r\n` and processing a file with lines ending with `\n`. You need to add this setting:

`settings.getFormat().setLineSeparator("\n");`

Or to make things easier, `settings.setLineSeparatorDetectionEnabled(true);`

Hope this helps.
Thank you for using our parsers!

**Comment by ozzioma** [comment]
Thanks!
Yes I'm on windows.
That fixed it, got me stumped all day.

PS: Would it be ok to suggest an update to the documentation?
Like take out the hidden getReader part and add the method directly in the examples.
You could add additional methods showing how to load file paths from the resources folder, 
local file system...and also using buffered readers etc.
IMO, that's the first thing newbies are going to have to figure out.

Next, complete and simple examples lead to less head scratching than edge case examples.
Or examples that do not address a use case.
I mean like this for parsing into a custom Java beans

```
private static final String csvpathPrices = "F:\\files\\nyse\\prices.csv";
    private static final String csvpathSecs = "F:\\files\\securities.csv";

    public static void LoadPrices() throws IOException {
        try (
                Reader reader = Files.newBufferedReader(Paths.get(csvpathPrices));
                FileReader reader2= new FileReader(new File(csvpathPrices))
        ) {
            BeanListProcessor<Prices> rowProcessor = new BeanListProcessor<Prices>(Prices.class);

            CsvParserSettings settings = new CsvParserSettings();
            settings.setRowProcessor(rowProcessor);

            settings.setHeaderExtractionEnabled(true);
            //settings.getFormat().setLineSeparator("\n");
            settings.setLineSeparatorDetectionEnabled(true);

            settings.setIgnoreLeadingWhitespacesInQuotes(false);
            settings.setIgnoreTrailingWhitespacesInQuotes(false);
            settings.trimQuotedValues(true);

            settings.setMaxColumns(10);
            settings.setNumberOfRecordsToRead(1000);

            CsvParser parser = new CsvParser(settings);
            parser.parse(reader);

            List<Prices> allRows = rowProcessor.getBeans();

            System.out.println("total rows->"+allRows.size());

            for (Prices price:allRows )
            {
                System.out.println(price);

            }
         
        }
```

Or like this demonstrating how to use routines for parsing CSV files into Java beans

```
private static final String csvpathPrices = "F:\\files\\nyse\\prices.csv";
try (
                Reader reader = Files.newBufferedReader(Paths.get(csvpathPrices));
                FileReader reader2= new FileReader(new File(csvpathPrices))
        ) {

  CsvParserSettings settings2 = new CsvParserSettings();
            settings2.setHeaderExtractionEnabled(true);
            settings2.getFormat().setLineSeparator("\n");
            settings2.setIgnoreLeadingWhitespacesInQuotes(false);
            settings2.setIgnoreTrailingWhitespacesInQuotes(false);
            settings.trimQuotedValues(true);
            settings2.setMaxColumns(10);
            settings2.setNumberOfRecordsToRead(200);

            CsvRoutines routines = new CsvRoutines(settings2);

            for (Prices bean : routines.iterate(Prices.class, reader2)) {
                System.out.println(bean);
            }
}
```
