### ISSUE TITLE
Truncate, Skip, Fail options when the data length is more than maxColumnLength

### ISSUE THREAD

**Issue by vishwanath-openprise** [uniVocity/univocity-parsers#288]
Current implementation always fails with:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 50
	at com.univocity.parsers.common.input.DefaultCharAppender.appendUntil(DefaultCharAppender.java:245) ~[univocity-parsers-2.5.8.jar:2.5.8]
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:139) ~[univocity-parsers-2.5.8.jar:2.5.8]
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:121) ~[univocity-parsers-2.5.8.jar:2.5.8]
	... 34 more
```
```
public char appendUntil(char ch, CharInput input, char stop1, char stop2) {
		for (; ch != stop1 && ch != stop2; ch = input.nextChar()) {
			chars[index++] = ch;
		}
		return ch;
	}
```

**Comment by jbax** [comment]
That's pretty much the intent: to fail fast before letting your program slow down/crash with an out of memory error if someone gives you a file that doesn't conform to the expected format. This setting is not meant to make the parser ignore the problem and try to proceed.

Hope this clarifies. Thank you for using our parsers!

**Comment by vishwanath-openprise** [comment]
Thank you for the clarification @jbax Thanks a lot for the parsers, they are great!
I am ready to contribute on this, if you think it would give some control knob for the parser users, if anyone really needs it. Let me know your thoughts!
