### ISSUE TITLE
Using multiple instances of univocity CsvParser yields java.lang.InterruptedException - null

### ISSUE THREAD

**Issue by M-F-K** [uniVocity/univocity-parsers#313]
multiple threads, each using its own instantiated univocity Csvparser gives the following stacktrace. Is this the same as in #195 , or can there be done something about it ( I really need to use one univocity instance pr. thread ) : 

com.univocity.parsers.common.TextParsingException: java.lang.InterruptedException - null
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Delimiters for detection=null
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=true
	Headers=null
	Ignore leading whitespaces=true
	Ignore leading whitespaces in quotes=false
	Ignore trailing whitespaces=true
	Ignore trailing whitespaces in quotes=false
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=com.univocity.parsers.common.processor.RowListProcessor
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\r\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
Internal state when error was thrown: line=0, column=0, record=0
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:369)
	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:245)
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:114)
	at ....GenericCSVParser.parseRow(GenericCSVParser.java:186)
	at ....GenericCSVParser.parse(GenericCSVParser.java:140)
	at ....GenericCSVParser.parseCsv(GenericCSVParser.java:112)
	at ....ImportService.lambda$processImportRows$11(ImportService.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.springframework.cloud.sleuth.instrument.async.LocalComponentTraceRunnable.run(LocalComponentTraceRunnable.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:350)
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharLoader.readBucket(ConcurrentCharLoader.java:73)
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharLoader.nextBucket(ConcurrentCharLoader.java:118)
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharInputReader.reloadBuffer(ConcurrentCharInputReader.java:109)
	at com.univocity.parsers.common.input.AbstractCharInputReader.updateBuffer(AbstractCharInputReader.java:192)
	at com.univocity.parsers.common.input.AbstractCharInputReader.start(AbstractCharInputReader.java:173)
	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:243)
	... 10 common frames omitted

**Comment by jbax** [comment]
If a thread has been interrupted there is not a lot to be done. The parser was configured to read the input in parallel and if something made it stop running it just can't proceed. This is generally normal but if you don't want to see this exception then set `readInputOnSeparateThread=false` so the parser won't spawn a separate thread that can be interrupted by your container.

Thank you for using our parsers!

**Comment by jbax** [comment]
If you have a reproducible test case that highlights some unexpected behavior, please reopen this issue with the test code.

**Comment by M-F-K** [comment]
@jbax thanks for your reply, - readInputOnSeparateThread=false did it. I'm just posting this for anybody having the same problem.
