### ISSUE TITLE
@Trim annotation on FixedWidt

### ISSUE THREAD

**Issue by PiotrDuz** [uniVocity/univocity-parsers#330]
Hello,
I have following issue:
I am using fixedWidthParser. I have a field Double in my bean class. When I read the text file, an error is thrown: 

```
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at com.univocity.parsers.conversions.ObjectConversion.execute(ObjectConversion.java:29)
	at com.univocity.parsers.common.fields.FieldConversionMapping.applyConversions(FieldConversionMapping.java:267)
	... 63 more
```

This is my BeanClass:
`@Headers(sequence = { "date", "number" }, extract = false, write = false)
public class ObjectCatBean
{

    @FixedWidth(value = 24, alignment = FieldAlignment.LEFT, padding = ' ')
    @Convert(conversionClass = DateConversion.class)
    @NullString(nulls = { " ", "" })
    @Parsed()
    public ZonedDateTime date;

    @Format(formats = "##0.00")
    @FixedWidth(value = 6, alignment = FieldAlignment.LEFT, padding = ' ')
    @NullString(nulls = { " ", "" })
    @Parsed()
    public Double number;

}`

My file that I am reading:
`2019/06/03-17:00:00.000  23.76`

and the read procedure:
`FixedWidthParserSettings settings = new FixedWidthParserSettings();
        settings.setAutoConfigurationEnabled(true);
        settings.trimValues(true);
        settings.getFormat().setLineSeparator("\n");

        BeanListProcessor<ObjectCatBean> processor = new BeanListProcessor<>(ObjectCatBean.class);
        settings.setProcessor(processor);

        FixedWidthParser parser = new FixedWidthParser(settings);

        File cat = new File(testPath, "catalogue/cat.dat");
        try (BufferedReader reader = new BufferedReader(new FileReader(cat)))
        {
            parser.parse(reader);
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }`

It is a very basic example... What am I missing?
Regards,

**Comment by PiotrDuz** [comment]
I have managed to solve it. The problem was in order of annotations. Format shall be below.
`@Parsed()
    @Trim
    @FixedWidth(value = 15 + 1, alignment = FieldAlignment.LEFT, padding = ' ')
    @NullString(nulls = { "" })
    @Format(formats = "0.000000")`

But now I have  anew problem - with alignment. 
Even that alignment is set to left for many fields in my Bean, it is working for String only. 
For Integers/ doubles it takes no effect, and they are aligned to the right. 

For example field annotated like this: 

`    @Parsed()
    @Trim
    @FixedWidth(value = 15 + 1, alignment = FieldAlignment.LEFT, padding = ' ')
    @NullString(nulls = { "" })
    @Format(formats = "0.000000")
    private Double diameter;`

Produces given output when written: 

2019/06/04-17:00:00.000 3.643512        10.426300       <-- original line
2019/06/04-17:00:00.000        3.643512                         <-- original line read and written again

Value 3.64... is now aligned to the right. 
Do I miss something? Any help appreciated.
Regards,
