### ISSUE TITLE
Fixed Width Nested annotation not working

### ISSUE THREAD

**Issue by jesusvillalbam** [uniVocity/univocity-parsers#442]
Hello,

I´m trying to figure it out how to solve this funcionality with your utility.

I have the same text file fixed width

0112345678902020110902300000000501087972202111111111101
050000000000001000

I,m trying to make two beans from this text file, i already do this:

```
public static void test() {
        FixedWidthParserSettings settings = new FixedWidthParserSettings();
        settings.setRecordEndsOnNewline(true);
        settings.setSkipTrailingCharsUntilNewline(true);

        final BeanListProcessor<FileHeader> fileHeaderProcessor = new BeanListProcessor<>(FileHeader.class);
        final BeanListProcessor<LotHeader> lotHeaderProcessor = new BeanListProcessor<>(LotHeader.class);
settings.setProcessor(fileHeaderProcessor);
        settings.setProcessor(lotHeaderProcessor);
        FixedWidthFields fileHeader = FixedWidthFields.forParsing(FileHeader.class);
        FixedWidthFields lotHeader = FixedWidthFields.forParsing(LotHeader.class);
        settings.addFormatForLookahead("01", fileHeader);
        settings.addFormatForLookahead("05", lotHeader);
        FixedWidthParser parser = new FixedWidthParser(settings);
        parser.parse(new InputStreamReader(DemoApplication.class.getResourceAsStream("/asobancaria_test.txt")));

        fileHeaderProcessor.getBeans();
    }
```

```
public class FileHeader {
    @Parsed
    @FixedWidth(from = 0, to = 2)
    private String recordType;
    @Parsed
    @FixedWidth(from = 2, to = 12)
    private String collectCompanyNIT;
    @Parsed
    @FixedWidth(from = 12, to = 20)
    private String collectDate;
    @Parsed
    @FixedWidth(from = 20, to = 23)
    private String collectEntityCode;
    @Parsed
    @FixedWidth(from = 23, to = 40)
    private String receivingCustomerAccountNumber;
    @Parsed
    @FixedWidth(from = 40, to = 48)
    private String fileDateGeneration;
    @Parsed
    @FixedWidth(from = 48, to = 52)
    private String fileHourGeneration;
    @Parsed
    @FixedWidth(from = 52, to = 53)
    private String fileModificator;
    @Parsed
    @FixedWidth(from = 53, to = 55)
    private String accountType;
    @Nested()
    private LotHeader lotHeader;

    // getters setters
}
```

```
public class LotHeader {

    @Parsed
    @FixedWidth(from = 0, to = 2)
    private String recordType;
    @Parsed
    @FixedWidth(from = 2, to = 15)
    private String collectServiceCode;
    @Parsed
    @FixedWidth(from = 15, to = 19)
    private String lotNumber;

   // Getters setters
}
```

I,m getting this error message

Exception in thread "main" java.lang.IllegalArgumentException: Start position '0' overlaps with one or more fields
	at com.univocity.parsers.fixed.FixedWidthFields.addField(FixedWidthFields.java:319)
	at com.univocity.parsers.fixed.FixedWidthFields.<init>(FixedWidthFields.java:186)
	at com.univocity.parsers.fixed.FixedWidthFields.forParsing(FixedWidthFields.java:119)
	at com.example.demo.DemoApplication.test(DemoApplication.java:84)
	at com.example.demo.DemoApplication.main(DemoApplication.java:22)

**Comment by jbax** [comment]
Can't use @Nested here. That's for values that appear in the same row. The annotations don't work to join the contents of multiple rows.

**Comment by jesusvillalbam** [comment]
If anyone is interested i solved this need and can be read it at https://github.com/jesusvillalbam/asobancaria-2001-file-parser

Feel free to make suggests
