### ISSUE TITLE
Selective header / fields conflict?

### ISSUE THREAD

**Issue by mlvn23** [uniVocity/univocity-parsers#46]
Thanks for this great library! It's very flexible so I continue to come back to it.

I'm currently using 1.6.0-SNAPSHOT, and I've encountered an issue when using the setHeaders / selectFields.

I have a test bean like this (in Scala):

```
    @BeanInfo
    @Headers(sequence = Array(
        "id", "timestamp", "symbol", "quantity", "isComplete", "datetime", "number"
    ))
    class BasicTypes() extends ToJsonString {

        @Parsed var id: Int = _
        @Parsed var quantity: Double = _
        @Parsed var timestamp: Long = _
        @Parsed var symbol: String = _
        @Parsed var isComplete: Boolean = _
        @Parsed var number: Numerals = _

        @Parsed
        @Convert(conversionClass = classOf[DateOptTimeConversion])
        var datetime: DateTime = _

        override def toString: String = toJsonString

    }
```

And my writer is like this:

```
    def writeCsv[T: Manifest](
        records: Seq[T], writer: Writer, headers: Option[Seq[String]] = None)
        (implicit tag: ClassTag[T]): Unit = {

        val cls = tag.runtimeClass.asInstanceOf[Class[T]]
        val processor = new BeanWriterProcessor[T](cls)

        val settings = new CsvWriterSettings
        settings.setRowWriterProcessor(processor)
        headers.foreach { h =>
            println("XXX=", h)
            //settings.setHeaders(h: _*)
            //settings.setHeaders("id")
            //settings.selectFields("timestamp")
        }

        val w = new CsvWriter(writer, settings)
        w.writeHeaders()
        w.processRecordsAndClose(records.asJava)

    }
```
If I don't override the setHeaders and selectFields, then it works. 
If I selective pick fields in a different order (e.g., quantity, symbol, number), then I would get an error.

Calling settings.selectFields("id") works:

```
id,timestamp,symbol,quantity,isComplete,datetime,number
1,,,,,,
9,,,,,,
100,,,,,,
```
Calling settings.selectFields("timestamp") doesn't work:

```
[info]   com.univocity.parsers.common.DataProcessingException: Error processing data conversions
[info] Internal state when error was thrown: charIndex=0, row=[null], columnIndex=0
[info]   at com.univocity.parsers.common.ConversionProcessor.handleConversionError(ConversionProcessor.java:206)
[info]   at com.univocity.parsers.common.ConversionProcessor.reverseConversions(ConversionProcessor.java:192)
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.reverseConversions(BeanConversionProcessor.java:373)
[info]   at com.univocity.parsers.common.processor.BeanWriterProcessor.write(BeanWriterProcessor.java:57)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecord(AbstractWriter.java:390)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecords(AbstractWriter.java:345)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecordsAndClose(AbstractWriter.java:316)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.writeCsv(ScalaCsv.scala:52)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.toCsvStr(ScalaCsv.scala:68)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$3.apply$mcV$sp(ScalaCsvTest.scala:55)
[info]   ...
[info]   Cause: java.lang.ArrayIndexOutOfBoundsException: 1
[info]   at com.univocity.parsers.common.ConversionProcessor.reverseConversions(ConversionProcessor.java:188)
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.reverseConversions(BeanConversionProcessor.java:373)
[info]   at com.univocity.parsers.common.processor.BeanWriterProcessor.write(BeanWriterProcessor.java:57)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecord(AbstractWriter.java:390)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecords(AbstractWriter.java:345)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecordsAndClose(AbstractWriter.java:316)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.writeCsv(ScalaCsv.scala:52)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.toCsvStr(ScalaCsv.scala:68)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$3.apply$mcV$sp(ScalaCsvTest.scala:55)
```
Calling setHeaders("id") doesn't work:
```
[info]   java.lang.ArrayIndexOutOfBoundsException: -1
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.mapFieldIndexes(BeanConversionProcessor.java:244)
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.mapFieldsToValues(BeanConversionProcessor.java:326)
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.reverseConversions(BeanConversionProcessor.java:361)
[info]   at com.univocity.parsers.common.processor.BeanWriterProcessor.write(BeanWriterProcessor.java:57)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecord(AbstractWriter.java:390)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecords(AbstractWriter.java:345)
[info]   at com.univocity.parsers.common.AbstractWriter.processRecordsAndClose(AbstractWriter.java:316)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.writeCsv(ScalaCsv.scala:52)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.toCsvStr(ScalaCsv.scala:68)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$3.apply$mcV$sp(ScalaCsvTest.scala:55)
```

**Comment by mlvn23** [comment]
I also tried it on 2.0.0-SNAPSHOT.

**Comment by jbax** [comment]
Thanks for reporting this bug. It's been fixed and a new 2.0.0-SNAPSHOT version has been built already,

**Comment by mlvn23** [comment]
@jbax, thanks for the quick turn-around, as usual. I tested this and it now works.

It looks like there's something missing on the read path of the BeanListProcessor. Using the same Bean,I have this partial csv:

```
        "quantity,symbol,id\r\n" +
        "23.4,IBM,1\r\n" +
        "9.55,WMT,9\r\n" +
        "79.7,the quick brown fox,100\r\n"
```
And this is my reader:

```
    def readCsv[T: Manifest](reader: Reader)
        (implicit tag: ClassTag[T]): Seq[T] = {

        val cls = tag.runtimeClass.asInstanceOf[Class[T]]
        val processor = new BeanListProcessor[T](cls)
        //val processor = new RowListProcessor()

        val settings = new CsvParserSettings
        settings.setRowProcessor(processor)
        settings.setHeaderExtractionEnabled(true)
        //settings.setHeaders("quantity")
        //settings.selectFields("quantity")

        val parser = new CsvParser(settings)
        parser.parse(reader)

        //processor.getBeans().asScala

        println(processor.getBeans())

        Seq.empty

    }
```
I'm getting this error:

```
[info]   com.univocity.parsers.common.DataProcessingException: Unexpected error processing input row [23.4, IBM, 1] using RowProcessor com.univocity.parsers.common.processor.BeanListProcessor.
[info] Internal state when error was thrown: line=2, charIndex=33, headers=[quantity, symbol, id], row=[23.4, IBM, 1]
[info]   at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:479)
[info]   at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:93)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.readCsv(ScalaCsv.scala:31)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.fromCsvStr(ScalaCsv.scala:66)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$5.apply$mcV$sp(ScalaCsvTest.scala:77)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$5.apply(ScalaCsvTest.scala:76)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$5.apply(ScalaCsvTest.scala:76)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.lang.IllegalStateException: Unknown field names: [timestamp]. Available fields are: [quantity, symbol, id]
[info]   at com.univocity.parsers.common.fields.FieldNameSelector.getFieldIndexes(FieldNameSelector.java:54)
[info]   at com.univocity.parsers.common.fields.AbstractConversionMapping.prepareExecution(FieldConversionMapping.java:283)
[info]   at com.univocity.parsers.common.fields.FieldConversionMapping.prepareExecution(FieldConversionMapping.java:96)
[info]   at com.univocity.parsers.common.ConversionProcessor.initializeConversions(ConversionProcessor.java:100)
[info]   at com.univocity.parsers.common.ConversionProcessor.applyConversions(ConversionProcessor.java:127)
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.createBean(BeanConversionProcessor.java:365)
[info]   at com.univocity.parsers.common.processor.BeanProcessor.createBean(BeanProcessor.java:36)
[info]   at com.univocity.parsers.common.processor.BeanProcessor.rowProcessed(BeanProcessor.java:51)
[info]   at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:471)
[info]   at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:93)
```

I understand that it's desirable to always get a fully formed bean most of the time, but maybe we can add an option that says "partial" is okay? I tried the selectFields / setHeaders, but it didn't help. Anyway, even if it did, I think it's still better if the parser could "auto-detect" the columns.

My use-case is for stock / commodity prices. Format could be:

[date,close]
[date,time,close]
[date,open,high,low,close,volume]
[date,open,high,low,close,volume, openInt]
[timestamp,open,high,low,close,volume]
[timestamp,open,high,low,close,volume,openInt]

I was hoping I could define one bean to cover all of them.

Thanks again in advance.

**Comment by mlvn23** [comment]
Let me just create a new issue for this.
