### ISSUE TITLE
BeanListProcessor cannot read fields selectively

### ISSUE THREAD

**Issue by mlvn23** [uniVocity/univocity-parsers#48]
It looks like there's something missing on the read path of the BeanListProcessor. Using the same Bean:

```
    @BeanInfo
    @Headers(sequence = Array(
        "id", "timestamp", "symbol", "quantity", "isComplete", "datetime", "number"
    ))
    class BasicTypes() extends ToJsonString {

        @Parsed var id: Int = _
        @Parsed var quantity: Double = _
        @Parsed var timestamp: Long = _
        @Parsed var symbol: String = _
        @Parsed var isComplete: Boolean = _
        @Parsed var number: Numerals = _

        @Parsed
        @Convert(conversionClass = classOf[DateOptTimeConversion])
        var datetime: DateTime = _

        override def toString: String = toJsonString

    }
```
I have this partial csv:
```
        "quantity,symbol,id\r\n" +
        "23.4,IBM,1\r\n" +
        "9.55,WMT,9\r\n" +
        "79.7,the quick brown fox,100\r\n"
```
And this is my reader:

```
    def readCsv[T: Manifest](reader: Reader)
        (implicit tag: ClassTag[T]): Seq[T] = {

        val cls = tag.runtimeClass.asInstanceOf[Class[T]]
        val processor = new BeanListProcessor[T](cls)
        //val processor = new RowListProcessor()

        val settings = new CsvParserSettings
        settings.setRowProcessor(processor)
        settings.setHeaderExtractionEnabled(true)
        //settings.setHeaders("quantity")
        //settings.selectFields("quantity")

        val parser = new CsvParser(settings)
        parser.parse(reader)

        //processor.getBeans().asScala

        println(processor.getBeans())

        Seq.empty

    }
```
I'm getting this error:

```
[info]   com.univocity.parsers.common.DataProcessingException: Unexpected error processing input row [23.4, IBM, 1] using RowProcessor com.univocity.parsers.common.processor.BeanListProcessor.
[info] Internal state when error was thrown: line=2, charIndex=33, headers=[quantity, symbol, id], row=[23.4, IBM, 1]
[info]   at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:479)
[info]   at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:93)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.readCsv(ScalaCsv.scala:31)
[info]   at com.extrategic.util.csv.univocity.ScalaCsv$.fromCsvStr(ScalaCsv.scala:66)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$5.apply$mcV$sp(ScalaCsvTest.scala:77)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$5.apply(ScalaCsvTest.scala:76)
[info]   at com.extrategic.util.csv.univocity.ScalaCsvTest$$anonfun$5.apply(ScalaCsvTest.scala:76)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.lang.IllegalStateException: Unknown field names: [timestamp]. Available fields are: [quantity, symbol, id]
[info]   at com.univocity.parsers.common.fields.FieldNameSelector.getFieldIndexes(FieldNameSelector.java:54)
[info]   at com.univocity.parsers.common.fields.AbstractConversionMapping.prepareExecution(FieldConversionMapping.java:283)
[info]   at com.univocity.parsers.common.fields.FieldConversionMapping.prepareExecution(FieldConversionMapping.java:96)
[info]   at com.univocity.parsers.common.ConversionProcessor.initializeConversions(ConversionProcessor.java:100)
[info]   at com.univocity.parsers.common.ConversionProcessor.applyConversions(ConversionProcessor.java:127)
[info]   at com.univocity.parsers.common.processor.BeanConversionProcessor.createBean(BeanConversionProcessor.java:365)
[info]   at com.univocity.parsers.common.processor.BeanProcessor.createBean(BeanProcessor.java:36)
[info]   at com.univocity.parsers.common.processor.BeanProcessor.rowProcessed(BeanProcessor.java:51)
[info]   at com.univocity.parsers.common.AbstractParser.rowProcessed(AbstractParser.java:471)
[info]   at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:93)
```

I understand that it's desirable to always get a fully formed bean most of the time, but maybe we can add an option that says "partial" is okay? I tried the selectFields / setHeaders, but it didn't help. Anyway, even if it did, I think it's still better if the parser could "auto-detect" the columns.

My use-case is for stock / commodity prices. Format could be:

```
[date,close]
[date,time,close]
[date,open,high,low,close,volume]
[date,open,high,low,close,volume, openInt]
[timestamp,open,high,low,close,volume]
[timestamp,open,high,low,close,volume,openInt]
```

I was hoping I could define one bean to cover all of them.

Thanks again in advance.

**Comment by jbax** [comment]
Fixed. Gosh this one was a pain in the neck. A new snapshot build has been released to include these changes.

**Comment by mlvn23** [comment]
THANK YOU. I'll give this a try in a day or two.

This is actually a killer feature. I can't make this work with Jackson CSV, and SuperCsv always requires explicit schema.
