### ISSUE TITLE
ArrayIndexOutOfBoundsException when using selectFields(Enum...) and Record.get...(Enum)

### ISSUE THREAD

**Issue by paul-popineau-ullink** [uniVocity/univocity-parsers#85]
Hello,
First, I'm just fan of the library, so powerful!
But I have a problem when using `Enum` to identify the columns I need in conjunction with the `Record`.

Here some example:
```java
CsvParserSettings settings = new CsvParserSettings();
settings.setHeaderExtractionEnabled(true);
settings.selectFields((Enum[]) MyEnum.values());
List<Record> records = parser.parseAllRecords(reader);
...
record.getString(MyEnum.CONSTANT2);
```

And a CSV sample:
```
<MyEnum.CONSTANT1>, <MyEnum.CONSTANT3>, Useless header, <MyEnum.CONSTANT2>
value, value, useless value, value
value, value, useless value, value
```

And the stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: 4
	at com.univocity.parsers.common.record.RecordMetaDataImpl.getValue(RecordMetaDataImpl.java:214)
	at com.univocity.parsers.common.record.RecordImpl.getString(RecordImpl.java:117)
```

So far I think it's a problem when reordering the selected fields, it works with 
```java
settings.setColumnReorderingEnabled(false);
```

**Comment by jbax** [comment]
Fixed in the latest commit. I'll release a SNAPSHOT build of version 2.1.1 to include this bugfix soon. 
Thank you!

**Comment by jbax** [comment]
2.1.1-SNAPSHOT released.

**Comment by paul-popineau-ullink** [comment]
Thanks !
